# Generated by Django 4.2.7 on 2024-01-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NykaaFrontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Reg Images')),
            ],
        ),
    ]
