# Generated by Django 4.2.7 on 2024-01-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NykaaFrontend', '0002_registerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='ConfirmPassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
