# Generated by Django 4.2.7 on 2024-01-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NykaaFrontend', '0004_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
