# Generated by Django 4.2.7 on 2024-01-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NykaaBackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Image',
            new_name='Image1',
        ),
        migrations.AddField(
            model_name='productdb',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='Product Images'),
        ),
    ]
